---
title: "한국의 인구 이동"
output: html_notebook
---

## Get data from kosis

http://kosis.kr/ups/ups_01List.jsp?pubcode=AD
or
http://kosis.kr/upsHtml/online.do?isOnline=Y&PART=G&pubcode=AD
http://kosis.kr/upsHtml/online/downSrvcFile.do?PUBCODE=AD&SEQ=2959&FILE_NAME=030117.xlsx
원하는 xlsx파일을 data/xls에 저장한 후 읽어들인다.

```{r}
require(readxl)
xls_file <- "data/xls/2015년_030117.xlsx"
xdf <- read_excel(xls_file)
head(xdf)
colnames(xdf)
```

전입지, 전출지, 계만 남기고 다른 컬럼들은 무시한다.
전입지, 전출지중에서 시군구 레벨만 남긴다. 
외부로의 이동만 포함

```{r}
df <- select_(xdf, from="전입지", to="전출지", value="계", mvalue=21, fvalue=39) %>%
  filter(from == '세종' | nchar(from)>2) %>%
  filter(to == '세종' | nchar(to)>2) %>%
  filter(from != to )

head(df)
```

제일많이 빠져나간 곳은 어딜까?

```{r}
df <- arrange(df, desc(value))  
head(df)
```

```{r}
sdf <- filter(df, value>1000)
ggplot(sdf, aes(value)) + geom_histogram(binwidth=500)
```

남녀간 이동의 차이
```{r}
ggplot(df, aes(mvalue - fvalue)) + geom_histogram(binwidth=5) +ylim(c(0,1000))
mean(df$mvalue-df$fvalue)
```

```{r fig.height=10, fig.width=10}
sdf <- filter(df, value>2000) %>% arrange(from)
require(circlize)
par(family='Apple SD Gothic Neo')
chordDiagram(sdf, annotationTrack = "grid",
  preAllocateTracks = list(track.height = 0.3))

# we go back to the first track and customize sector labels
circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
  xlim = get.cell.meta.data("xlim")
  ylim = get.cell.meta.data("ylim")
  sector.name = get.cell.meta.data("sector.index")
  circos.text(mean(xlim), ylim[1], sector.name, facing = "clockwise",
    niceFacing = TRUE, adj = c(0, 0.5))
}, bg.border = NA) # here set bg.border to NA is important
```

네트워크로 표현해볼까.

```{r}
library(igraph)
ndf <- filter(df, value>1000) %>% arrange(from)
g <- graph_from_data_frame(ndf)
```

그려보자

```{r fig.height=20, fig.width=20}
par(family='Apple SD Gothic Neo')
edgeScale = 0.002
plot(g, vertex.size=2, 
     vertex.label.family='Apple SD Gothic Neo', vertex.label.cex=2,
     edge.width = E(g)$value * edgeScale, edge.arrow.size=E(g)$value * edgeScale * 0.4,
     edge.color = rgb(0.2,0.2,0.2,.2))
```




