---
title: "Naver Trends"
output: html_notebook
---


```{r}
# library(devtools)
# install_github("yonghah/naveRtrends")
```

네이버 검색어의 인기가 시간에 따라 어떻게 변하는지 살펴보자.

```{r}
library(naveRtrends)
words <- c("팥빙수")
start <- "20080101"
end <- "20161130"
df <- ntrends(words, start, end)
head(df)

```

```{r}
library(ggplot2)
ggplot(df, aes(x=period, y=value)) +
  geom_bar(stat='identity', fill='#652799') 

```


잉크를 아껴보자!

```{r}
ggplot(df, aes(x=period, y=value)) +
  geom_point(color="#943423", size=0.1)
```

너무 아꼈다!

```{r}
ggplot(df, aes(x=period, y=value)) +
  geom_line(color="#943423", size=0.5)
```


일주일 간격은 너무 조밀하다!
```{r}
library(dplyr)
mdf <- group_by(df, period=as.Date(cut(period, "1 month")), topic) %>%
  summarise(value=sum(value))
head(mdf)
```


```{r}
ggplot(mdf, aes(x=period, y=value)) +
  geom_bar(stat="identity") 
```

이번에는 복수의 검색어를 이용해보자.

```{r}
words <- c("팥빙수", "귤")
start <- "20080101"
end <- "20161130"
df2 <- ntrends(words, start, end)
```
그래프를 그려보자

```{r}
ggplot(df2, aes(x=period, y=value)) +
  geom_point()
```

검색어별로 색깔을 다르게 주는게 좋겠군!

```{r}
ggplot(df2, aes(x=period, y=value)) +
  geom_point(aes(color=topic))
```

```{r}
ggplot(df2, aes(x=period, y=value)) +
  geom_line(aes(color=topic))
```

여러 시리즈를 비교하는 다른 방법

```{r}
ggplot(df2, aes(x=period, y=value)) +
  geom_line(aes(color=topic)) +
  facet_grid(topic~.)
```

이번에도 한달 단위로 묶어봅시다.
```{r}
mdf2 <- group_by(df2, period=as.Date(cut(period, "1 month")), topic) %>%
  summarise(value=sum(value))
```

```{r}
ggplot(mdf2, aes(x=period, y=value)) +
  geom_bar(stat="identity", aes(fill=topic)) +
  facet_grid(topic~.)
```

```{r}
ggplot(mdf2, aes(x=period, y=value)) +
  geom_bar(stat="identity", aes(fill=topic), position="dodge")   # fill, stack, dodge
  
```



```{r}
words <- c("러블리즈", "여자친구", "마마무", "레드벨벳", "트와이스")
start <- "20140101"
end <- "20161130"
bdf <- ntrends(words, start, end)
head(bdf)
```

라인 그래프를 그려보자

```{r}
par(family='Apple SD Gothic Neo')
theme_set(theme_gray(base_family='Apple SD Gothic Neo'))
ggplot(bdf, aes(x=period, y=value, group=topic)) + 
  geom_line(aes(color=topic))

```

```{r}

mbdf <- group_by(bdf, period=as.Date(cut(period, "1 month")), topic) %>%
  summarise(value=sum(value))
ggplot(bdf, aes(x=period, y=topic)) + 
  geom_tile(aes(fill=values)) +
  scale_fill_continuous(low="#ffffff", high="#d334e4") 

```

```{r}
require(streamgraph)

mbdf <- group_by(bdf, period=as.Date(cut(period, "1 month")), topic) %>%
  summarise(value=sum(value))

streamgraph(mbdf, "topic", "value", "period", interpolate="cardinal") %>% 
  sg_axis_x(20, "period", "%Y") %>%
  sg_fill_brewer("Dark2")
```


```{r}
wbdf2 <- group_by(bdf, period=as.Date(cut(period, "2 week")), topic) %>%
  summarise(value=sum(value))

ggplot(wbdf2, aes(x=period, y=value)) +
  geom_bar(stat="identity", aes(fill=topic)) +
  facet_grid(topic~.)
```
 